

# class MyClass:
#     def _init__(self, bien) -> None:
#         self.__var = bien
# obj = MyClass()
# print(obj.__var)


fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
my_favorite_fruits = fruits [5:]
my_favorite_fruits.insert(1, "peach")
print (my_favorite_fruits)
# x = 0
# for i in range(5):
#     for j in range(1, 10, 2):
#         x += 1
# print(x)

# print('Ben', 25, 'Califonia',sep='--')


# def xuatSoLe(batDau, ketThuc):
#     i = batDau
#     while i < ketThuc:
#         if i & 1 != 0:
#             print(i)
#         i += 1
# xuatSoLe (10, 20)
